import { Activity } from '../types';

export const DEMO_ACTIVITIES: Record<string, Activity> = {
  '1': { id: '1', creatorId: 'u1', creatorName: 'Rahul S.', title: 'Sunday Morning Tennis', interest: 'tennis', description: 'Looking for a partner for a friendly match. Intermediate level preferred. Court is booked, just need a partner!', date: '2026-05-18', time: '07:00', location: { name: 'Koramangala Tennis Court', address: '3rd Block, Koramangala, Bengaluru', city: 'Bengaluru', lat: 12.934, lng: 77.616 }, slots: 2, joinedCount: 0, participants: [], pendingRequests: [], genderPreference: 'any', skillLevel: 'intermediate', status: 'open', createdAt: '2026-05-12T10:00:00Z' },
  '2': { id: '2', creatorId: 'u2', creatorName: 'Priya M.', title: 'Badminton Evening Session', interest: 'badminton', description: 'Fun doubles game. All skill levels welcome! Shuttles provided.', date: '2026-05-14', time: '18:30', location: { name: 'HSR Badminton Club', address: 'HSR Layout Sector 2, Bengaluru', city: 'Bengaluru', lat: 12.912, lng: 77.641 }, slots: 4, joinedCount: 2, participants: ['u3', 'u4'], pendingRequests: [], genderPreference: 'any', skillLevel: 'any', status: 'open', createdAt: '2026-05-12T14:00:00Z' },
  '3': { id: '3', creatorId: 'u5', creatorName: 'Amit K.', title: 'Cubbon Park Morning Run', interest: 'running', description: '5K easy run. Bring your energy! We meet at Gate 1 and run together.', date: '2026-05-13', time: '06:00', location: { name: 'Cubbon Park Gate 1', address: 'Kasturba Road, Bengaluru', city: 'Bengaluru', lat: 12.979, lng: 77.593 }, slots: 5, joinedCount: 4, participants: ['demo_user', 'u6', 'u7', 'u8'], pendingRequests: [], genderPreference: 'any', skillLevel: 'beginner', status: 'open', createdAt: '2026-05-11T20:00:00Z' },
  '4': { id: '4', creatorId: 'u9', creatorName: 'Sneha R.', title: 'Friday Evening Yoga', interest: 'yoga', description: 'Relaxing outdoor yoga session. Bring your mat. Suitable for all levels.', date: '2026-05-15', time: '17:30', location: { name: 'Lalbagh Botanical Garden', address: 'Lalbagh, Bengaluru', city: 'Bengaluru', lat: 12.950, lng: 77.585 }, slots: 8, joinedCount: 3, participants: ['u10', 'u11', 'u12'], pendingRequests: [], genderPreference: 'any', skillLevel: 'any', status: 'open', createdAt: '2026-05-12T08:00:00Z' },
  '5': { id: '5', creatorId: 'u11', creatorName: 'Dev P.', title: 'Football — 5-a-side', interest: 'football', description: 'Friendly 5-a-side. Ground is booked, need 4 more players. Come ready to play!', date: '2026-05-17', time: '07:00', location: { name: 'Kanteerava Stadium Ground', address: 'Kasturba Road, Bengaluru', city: 'Bengaluru', lat: 12.975, lng: 77.594 }, slots: 4, joinedCount: 1, participants: ['u13'], pendingRequests: [], genderPreference: 'male', skillLevel: 'any', status: 'open', createdAt: '2026-05-12T09:00:00Z' },
  'my1': { id: 'my1', creatorId: 'demo_user', creatorName: 'You', title: 'Weekend Badminton', interest: 'badminton', description: 'Casual doubles, all welcome. Shuttles provided.', date: '2026-05-17', time: '08:00', location: { name: 'Indiranagar Badminton Club', address: 'Indiranagar, Bengaluru', city: 'Bengaluru', lat: 12.978, lng: 77.641 }, slots: 4, joinedCount: 2, participants: ['u1', 'u2'], pendingRequests: ['u3'], genderPreference: 'any', skillLevel: 'any', status: 'open', createdAt: '2026-05-12T10:00:00Z' },
};

export const getDemoList = () => Object.values(DEMO_ACTIVITIES);

export const addActivity = (activity: import('../types').Activity) => {
  DEMO_ACTIVITIES[activity.id] = activity;
};
