import { Activity } from '../types';

export const DEMO_ACTIVITIES: Record<string, Activity> = {
  '1': { id: '1', creatorId: 'u1', creatorName: 'Rahul S.', title: 'Sunday Morning Tennis', interest: 'tennis', description: 'Looking for a partner for a friendly match. Intermediate level preferred. Court is booked, just need a partner!', date: '2026-05-04', time: '07:00', location: { name: 'Koramangala Tennis Court', address: '3rd Block, Koramangala, Bengaluru', city: 'Bengaluru', lat: 12.934, lng: 77.616 }, slots: 2, joinedCount: 0, participants: [], pendingRequests: [], genderPreference: 'any', skillLevel: 'intermediate', status: 'open', createdAt: '2026-04-27T10:00:00Z' },
  '2': { id: '2', creatorId: 'u2', creatorName: 'Priya M.', title: 'Badminton Evening Session', interest: 'badminton', description: 'Fun doubles game. All skill levels welcome! Shuttles provided.', date: '2026-04-30', time: '18:30', location: { name: 'HSR Badminton Club', address: 'HSR Layout Sector 2, Bengaluru', city: 'Bengaluru', lat: 12.912, lng: 77.641 }, slots: 4, joinedCount: 2, participants: ['u3', 'u4'], pendingRequests: [], genderPreference: 'any', skillLevel: 'any', status: 'open', createdAt: '2026-04-26T14:00:00Z' },
  '3': { id: '3', creatorId: 'u5', creatorName: 'Amit K.', title: 'Cubbon Park Morning Run', interest: 'running', description: '5K easy run. Bring your energy! We meet at Gate 1 and run together.', date: '2026-04-29', time: '06:00', location: { name: 'Cubbon Park Gate 1', address: 'Kasturba Road, Bengaluru', city: 'Bengaluru', lat: 12.979, lng: 77.593 }, slots: 5, joinedCount: 4, participants: ['demo_user', 'u6', 'u7', 'u8'], pendingRequests: [], genderPreference: 'any', skillLevel: 'beginner', status: 'open', createdAt: '2026-04-25T20:00:00Z' },
  '4': { id: '4', creatorId: 'u9', creatorName: 'Sneha R.', title: 'Coffee & Networking', interest: 'coffee', description: 'Startup folks, freelancers, anyone! Just a chill chat over coffee. No agenda, just good conversations.', date: '2026-05-02', time: '10:30', location: { name: 'Third Wave Coffee', address: 'Indiranagar 100ft Road, Bengaluru', city: 'Bengaluru', lat: 12.978, lng: 77.641 }, slots: 4, joinedCount: 1, participants: ['u10'], pendingRequests: [], genderPreference: 'any', status: 'open', createdAt: '2026-04-27T08:00:00Z' },
  '5': { id: '5', creatorId: 'u11', creatorName: 'Dev P.', title: 'Weekend Movie — Avengers', interest: 'movies', description: 'Anyone else up for the 3pm show at PVR? Will book a group. Snacks on me!', date: '2026-05-03', time: '15:00', location: { name: 'PVR Cinemas', address: 'Forum Mall, Koramangala, Bengaluru', city: 'Bengaluru', lat: 12.935, lng: 77.610 }, slots: 6, joinedCount: 2, participants: ['u12', 'u13'], pendingRequests: [], status: 'open', createdAt: '2026-04-27T09:00:00Z' },
  'my1': { id: 'my1', creatorId: 'demo_user', creatorName: 'You', title: 'Weekend Badminton', interest: 'badminton', description: 'Casual doubles, all welcome. Shuttles provided.', date: '2026-05-10', time: '08:00', location: { name: 'Indiranagar Badminton Club', address: 'Indiranagar, Bengaluru', city: 'Bengaluru', lat: 12.978, lng: 77.641 }, slots: 4, joinedCount: 2, participants: ['u1', 'u2'], pendingRequests: ['u3'], genderPreference: 'any', skillLevel: 'any', status: 'open', createdAt: '2026-04-28T10:00:00Z' },
};

export const getDemoList = () => Object.values(DEMO_ACTIVITIES);

export const addActivity = (activity: import('../types').Activity) => {
  DEMO_ACTIVITIES[activity.id] = activity;
};
